spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tarefas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED

flyway:
  baseline-on-migrate: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
